### PR TITLE
Add Flask-CORS project

### PR DESCRIPTION
**Pull request by corydolphin**
Would love to get this up on the [extension registry](http://flask.pocoo.org/extensions/). Users have requested it be listed there.

Secondly, what are the necessary steps to make this an "approved" extension? I believe I have followed all guidelines and would welcome a review.

### CODE REVIEW

**Comment by immunda** [comment]
I'm not actually au fait on that and who would ultimately make the decision. However, as this project was intended to increase the bus factor of Flask and associated ecosystem I would think it's not sensible for @mitsuhiko to have to auth every project. Any thoughts @untitaker?

**Comment by untitaker** [comment]
We're in the middle of updating the extension guidelines, mostly relaxing them. I'd like to delay all extension reviewing post 1.0, but even then I'm not sure if we can gather the necessary resources to 1.) Make the flask website mirror the info in this repo 2.) Review all extensions

**Comment by immunda** [comment]
Sounds sensible. Regarding updating the extensions on the Flask website, is there a repo where it currently lives that I can submit a PR to?

**Comment by untitaker** [comment]
https://github.com/mitsuhiko/flask-website

Not sure if this auto-updates or if Armin has to deploy manually though.

**Comment by corydolphin** [comment]
Sadly it seems flask-website has not been updated in a year.

Thanks for merging this.

**Pull request merged**
